routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.auth.login');
});

Route::get('/dashboard', function () {
    return view('front.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__.'/auth.php';

//Front

// Route::get('/', function () {
//     return view('front.dashboard');
// })->name('dashboard');

Route::get('/company', function () {
    return view('front.company');
})->name('company');

Route::get('/foo', function () {
    return view('front.dashboard');
})->name('foo');

Route::get('/bar', function () {
    return view('front.dashboard');
})->name('bar');

//Back

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('front.layouts.app');
    }
}

app/View/Components/BackLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BackLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('back.layouts.app');
    }
}

app/View/Components/FrontLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FrontLayout extends Component
{
    public $section;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($section)
    {
        $this->section = $section;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('front.layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('front.layouts.guest');
    }
}

app/View/Components/Header.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Header extends Component
{
    public $section;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($section)
    {
        $this->section = $section;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.header');
    }
}

resources/views/back/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ES_es">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		
		<title>{{ $title ?? '' }}</title>
		<meta name="description" content="{{ $description ?? '' }}">
		<meta name="robots" content="noindex, nofollow">
		
		<link rel="shortcut icon" href="/img/favicon.png"  />
		@vite(['resources/css/app.css', 'resources/js/app.js'])
	
	</head>
	<body class="font-nunito text-gray antialiased">
		@include('front.layouts.sidebar')
		
		{{ $slot }}
	</body>
</html>

resources/views/back/layouts/menu.blade.php
<div class="flex flex-col justify-between h-full w-full">
	<div class="p-8">
		<ul class="leading-10 text-lg font-semibold">
			<x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
				<x-icons.home class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Dashboard
			</x-nav-link>
			<x-nav-link :href="route('company')" :active="request()->routeIs('company')">
				<x-icons.company class="{{ request()->routeIs('company') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Empresa
			</x-nav-link>
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.worker class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Trabajadores
			</x-nav-link>
			<x-nav-link :href="route('foo')" :active="request()->routeIs('foo')">
				<x-icons.machine class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Máquinas
			</x-nav-link>
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.company class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Obras
			</x-nav-link>
		</ul>
	</div>
	<div>
		<hr class="w-full border-blue-lighter">
		<div class="flex text-lg font-semibold bottom-1 px-8 py-4">
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.doc class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Documentación
			</x-nav-link>
		</div>
		<div class="bg-blue-dark flex justify-between text-sm px-2 py-1">
			<span class="flex">
				<img class="mr-1.5" src="{{ Vite::asset('resources/images/icons/phone.svg') }}" alt="Teléfono MONDO Ibérica" width="15" height="15">
				976 123 456
			</span>
			<span class="flex">
				<img class="mr-1.5" src="{{ Vite::asset('resources/images/icons/email.svg') }}" alt="E-mail MONDO Ibérica" width="15" height="15">
				foobar@foobar.com
			</span>
		</div>
	</div>
</div>

resources/views/front/company.blade.php
<x-front-layout section="empresa">
	<h2 class="shadow-xl border border-gray-100 rounded-lg px-6 py-4 text-blue uppercase font-semibold font-bebas text-2xl tracking-wider mb-4">Rechazados</h2>
	<table class="table-auto w-full">
		<thead class="text-left text-black border-b-2 border-black text-lg">
			<tr>
				<th>Documento</th>
				<th>Estado</th>
				<th>Fecha de subida</th>
				<th></th>
			</tr>
		</thead>
		<tbody class="font-semibold leading-8">
			<tr>
				<td>CIF / NIF / NIE</td>
				<td><x-badge color="red">Rechazado</x-badge></td>
				<td>04/03/2022</td>
			</tr>
			<tr>
				<td>Escritura de constitución de empresa y apoderamiento</td>
				<td>Rechazado</td>
				<td>04/03/2022</td>
			</tr>
			<tr>
				<td>Alta Seguridad Social</td>
				<td>Rechazado</td>
				<td>04/03/2022</td>
			</tr>
		</tbody>
	</table>


</x-front-layout>

resources/views/front/dashboard.blade.php
<x-front-layout section="dashboard">
	<div class="grid grid-cols-2 gap-6">
		<div class="mb-6">
			<h2 class="uppercase font-bebas text-blue text-2xl mb-3">Empresa</h2>
			<div class="shadow-xl border border-gray-100 rounded-lg h-72 p-8">
				<h3 class="border-b-2 border-black uppercase font-semibold text-black mb-6">Estado de documentos</h3>
				<div class="grid grid-cols-4 gap-3 h-4/5">
					<x-card-status color="red" message="Rechazados" :count="10">Rechazados</x-card-status>
					<x-card-status color="blue" message="Pendientes" :count="10">Pendientes</x-card-status>
					<x-card-status color="orange" message="En revisión" :count="10">En revisión</x-card-status>
					<x-card-status color="green" message="Aceptados" :count="10">Aceptados</x-card-status>
				</div>
			</div>
		</div>
		<div class="mb-6">
			<h2 class="uppercase font-bebas text-blue text-2xl mb-3">Trabajadores</h2>
			<div class="shadow-xl border border-gray-100 rounded-lg h-72 p-8">
				<h3 class="border-b-2 border-black uppercase font-semibold text-black mb-6">Estado de documentos</h3>
				<div class="grid grid-cols-4 gap-3 h-4/5">
					<x-card-status color="red" message="Rechazados" :count="10">Rechazados</x-card-status>
					<x-card-status color="blue" message="Pendientes" :count="10">Pendientes</x-card-status>
					<x-card-status color="orange" message="En revisión" :count="10">En revisión</x-card-status>
					<x-card-status color="green" message="Aceptados" :count="10">Aceptados</x-card-status>
				</div>
			</div>
		</div>
		<div class="mb-6">
			<h2 class="uppercase font-bebas text-blue text-2xl mb-3">Máquinas</h2>
			<div class="shadow-xl border border-gray-100 rounded-lg h-72 p-8">
				<h3 class="border-b-2 border-black uppercase font-semibold text-black mb-6">Estado de documentos</h3>
				<div class="grid grid-cols-4 gap-3 h-4/5">
					<x-card-status color="red" message="Rechazados" :count="10">Rechazados</x-card-status>
					<x-card-status color="blue" message="Pendientes" :count="10">Pendientes</x-card-status>
					<x-card-status color="orange" message="En revisión" :count="10">En revisión</x-card-status>
					<x-card-status color="green" message="Aceptados" :count="10">Aceptados</x-card-status>
				</div>
			</div>
		</div>
		<div class="mb-6">
			<h2 class="uppercase font-bebas text-blue text-2xl mb-3">Obras</h2>
			<div class="shadow-xl border border-gray-100 rounded-lg h-72 p-8">
				<h3 class="border-b-2 border-black uppercase font-semibold text-black mb-6">Estado de documentos</h3>
				<div class="grid grid-cols-4 gap-3 h-4/5">
					<x-card-status color="red" message="Rechazados" :count="10">Rechazados</x-card-status>
					<x-card-status color="blue" message="Pendientes" :count="10">Pendientes</x-card-status>
					<x-card-status color="orange" message="En revisión" :count="10">En revisión</x-card-status>
					<x-card-status color="green" message="Aceptados" :count="10">Aceptados</x-card-status>
				</div>
			</div>
		</div>
	</div>


</x-front-layout>

resources/views/front/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ES_es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <meta name="description" content="{{ $description ?? '' }}">
    <meta name="robots" content="noindex, nofollow">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>

<body class="font-nunito text-gray antialiased max-w-10xl mx-auto">
    <div class="flex">
        {{-- Sidebar --}}
        <div class="lg:w-1/5 2xl:w-2/12">
            @include('front.layouts.sidebar')

            {{-- navigation from breeze --}}
            {{-- @include('front.layouts.navigation') --}}
        </div>

        {{-- Header --}}
        <div class="lg:w-4/5 2xl:w-10/12">
            <x-header section="{{ $section ?? '' }}" />
            
            {{-- Main --}}
            <div class="px-6">
                {{ $slot }}
            </div>
        </div>
    </div>
</body>

</html>

resources/views/front/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="ES_es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        {{-- <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap"> --}}

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/front/layouts/menu.blade.php
<div class="flex flex-col justify-between h-full w-full">
	<div class="p-8">
		<ul class="leading-10 text-lg font-semibold">
			<x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
				<x-icons.home class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Resumen
			</x-nav-link>
			<x-nav-link :href="route('company')" :active="request()->routeIs('company')">
				<x-icons.company class="{{ request()->routeIs('company') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Empresa
			</x-nav-link>
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.worker class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Trabajadores
			</x-nav-link>
			<x-nav-link :href="route('foo')" :active="request()->routeIs('foo')">
				<x-icons.machine class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Máquinas
			</x-nav-link>
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.company class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Obras
			</x-nav-link>
		</ul>
	</div>
	<div>
		<hr class="w-full border-blue-lighter">
		<div class="flex text-lg font-semibold bottom-1 px-8 py-4">
			<x-nav-link :href="route('bar')" :active="request()->routeIs('bar')">
				<x-icons.doc class="{{ request()->routeIs('dashboard') ? 'fill-white' : 'fill-blue-lighter' }}h-5 w-5 mr-3"/>
				Documentación
			</x-nav-link>
		</div>
		<div class="bg-blue-dark flex justify-between text-xs px-2 py-1">
			<span class="flex">
				<img class="mr-1.5" src="{{ Vite::asset('resources/images/icons/phone.svg') }}" alt="Teléfono MONDO Ibérica" width="15" height="15">
				976 123 456
			</span>
			<span class="flex">
				<img class="mr-1.5" src="{{ Vite::asset('resources/images/icons/email.svg') }}" alt="E-mail MONDO Ibérica" width="15" height="15">
				foobar@foobar.com
			</span>
		</div>
	</div>
</div>

resources/views/front/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/front/layouts/sidebar.blade.php
<nav class="bg-blue text-white flex items-start flex-col h-screen">
	<div class="pt-8 px-8">
		<img class="bg-white" src="{{ Vite::asset('resources/images/mondo.svg') }}" width="250" alt="MONDO Ibérica">
	</div>
		@include('front.layouts.menu')
</nav>

resources/views/notinuse.blade.php
<div class="bg-red-50 bg-blue-50 bg-green-50 bg-orange-50 bg-red-500 bg-blue-500 bg-green-500 bg-orange-500 bg-red bg-blue bg-green bg-orange text-red-500 text-blue-500 text-green-500 text-orange-500"></div>